name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone master branch
        uses: actions/checkout@v3.3.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: ${{ github.repository }}
          TARGET_BRANCH: pages
        run: |
          npm install && \
          npm run build && \
          cd public && \
          git config --global --add safe.directory "*" && \
          git init -b master && \
          git config user.name ${{ github.actor }} && \
          git config user.email ${{ github.actor }}@users.noreply.github.com && \
          git add . && \
          git commit -m "Deploy to GitHub Pages" && \
          git push --force "https://username:${ACCESS_TOKEN}@${TARGET_REPO}.git" master:${TARGET_BRANCH}