name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone master branch
        uses: actions/checkout@v3.3.0
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: ${{ github.repository }}
          TARGET_BRANCH: pages
        run: |
          git config --global --add safe.directory "*" && \
          git config --global user.name ${{ github.actor }} && \
          git config --global user.email ${{ github.actor }}@users.noreply.github.com && \
          npm install && \
          npm run build && \
          pushd public && \
          git init -b master && \
          git add . && \
          git commit -m "Auto Deploy" && \
          git push --force "https://username:${ACCESS_TOKEN}@github.com/${TARGET_REPO}.git" master:${TARGET_BRANCH}
          popd && \
          git add db.json && \
          git commit -m "Update db.json" && \
          git push "https://username:${ACCESS_TOKEN}@github.com/${TARGET_REPO}.git" master:${{ github.ref }}